### ISSUE TITLE
Replace references to deprecated Boston housing prices In ReadMe

### ISSUE THREAD

**Issue by LipeiranNJU** [shap/shap#2844] opened 2023-01-28 09:24 UTC
boston housing prices in ReadMe has replaced by California housing Price. But in readme document, with explaining tree model, the sample also uses boston housing price. I think it may be confused for some greeners when use it.

**Comment by thatlittleboy** [comment] 2023-07-23 13:51
Closing this as duplicate of #2322

**Closed as not planned by thatlittleboy** 2023-07-23 13:51 UTC
Labels: documentation
