### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ahmedabbas81** [shap/shap#908] opened 2019-11-22 17:10 UTC
Dear all,

In order to get the input contributions to 2 hidden layers NN output and the NN is NOT ### convolutional NN

e = shap.DeepExplainer(model, background)

Does the above line set the reference activation for every neuron in the network?

shap_values = e.shap_values(x_test[1:5])

and this line gets the contributions in the 3D list shap_values? It has the contributions of every input feature in every input instance to each of the output neurons, is that correct?

And there are no more code lines required in the code.

Do I understand correctly?
Looking forward for an answer.

Thanks

**Comment by farh33n** [comment] 2019-11-29 06:51
Duplicate of #915

**Closed as completed** 2019-12-11 23:38 UTC
