### ISSUE TITLE
ENH: New release

### ISSUE THREAD

**Issue by PrimozGodec** [shap/shap#2989] opened 2023-06-14 11:42 UTC
### Problem Description

I am really happy that this package started to maintain gain. Thank you, all new maintainers. :) 

Since some important fixes have been made (for example, https://github.com/slundberg/shap/issues/2918, which solves problems using SHAP with the newer Numpy versions.), I would be really happy to see a new release at PyPI. One additional reason is also that Mac arm wheels are not available.

As an author of the `build_wheels.yml` script, I am happy to help you with the release. 

- [X] I have checked the issue tracker for duplicate issues.
- [ ] I'd be interested in making a PR to implement this feature

**Comment by dsgibbons** [comment] 2023-06-14 22:13
Is this not a duplicate of #2979 @PrimozGodec? We would be interested in your help for the next release.

**Closed as completed** 2023-06-15 00:38 UTC
