### ISSUE TITLE
Questions: Any plans of extending support to H2O.ai models(including ensembles)?

### ISSUE THREAD

**Issue by nronqsr** [shap/shap#224] opened 2018-08-15 20:01 UTC

**Comment by slundberg** [comment] 2018-08-16 00:43
Someone from H2O told me they are using Tree SHAP already in some of their stuff, but I don't use their libraries right now so I don't know where. Is there a specific scenario you want to use SHAP?

**Comment by nronqsr** [comment] 2018-08-16 01:12
They do have shapley values, but only on their enterprise platform. The open version, H2O, does not.

I am currently using H2O because of their automl function. It makes model generation/selection pretty painless. They also handle categorical variables very cleanly. In all, its great for getting models that are ready to predict.

H2O doesn't have much in the way of feature attribution though. SHAP seems to be the king of the hill right now and I would prefer to run SHAP against the actual model and not a sci-kit based model with the same parameters. That way I can dig into odd predictions with certainty that the outliers are directly related to the model from h2o.

**Comment by slundberg** [comment] 2018-08-18 00:28
Ah, I see. If someone sends in a PR then I am happy to merge it, but I am not going to actively try and reproduce what seems like one of their enterprise features.

**Comment by dnks23** [comment] 2018-12-05 09:47
Would really appreciate support for h2o.ai models as well!

**Comment by pstoyanov** [comment] 2019-04-06 08:48
In case someone missed it: 

As of 3.24.0.1, the free/open H2O supports TreeSHAP (GBM and XGBoost) -- see the [blog post](https://www.h2o.ai/blog/h2o-release-3-24-yates/) on their site.

Many thanks to all who worked on this, certainly makes life much easier (and easier to understand).

**Comment by jphall663** [comment] 2019-08-01 19:13
We also added support for random forest recently - thanks to @navdeep-G.

**Comment by detrin** [comment] 2023-08-26 20:00
@thatlittleboy Candidate for closing?

**Comment by thatlittleboy** [comment] 2023-08-27 01:47
Closing due to inactivity, if there are more specific H2O model types that need SHAP support, please raise a separate issue.

**Closed as completed** 2023-08-27 01:47 UTC
