### ISSUE TITLE
spelling mistakes are everywhere in docs

### ISSUE THREAD

**Issue by yichudu** [shap/shap#2725] opened 2022-10-13 07:08 UTC
Too many spelling mistakes in [shap.readthedocs.io](https://shap.readthedocs.io/en/latest/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20Shapley%20values.html), such as `becuase`, `interesection` , `fundemental ` ...., etc.  
Meanwhile , the [Edit on GitHub](https://github.com/slundberg/shap/blob/master/docs/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20Shapley%20values.ipynb) link is also unavailable.

**Comment by thatlittleboy** [comment] 2023-06-04 08:15
Spelling fixes will be fixed in #2967.

Marking as duplicate of #2237 and #1600 in the meantime.

**Closed as not planned by thatlittleboy** 2023-06-04 08:15 UTC
Labels: documentation
