### ISSUE TITLE
Top N features that are responsible for the local SHAP value

### ISSUE THREAD

**Issue by derigod** [shap/shap#1517] opened 2020-10-12 16:57 UTC
I've been trying to use SHAP values in my ML to help understand the contribution of each feature on the local outcome.  I understand that SHAP values of all features sum up to explain why the prediction was different from the baseline value. This allows us to decompose a prediction in a graph. 

My output will need rank the features in terms of contribution to the local value in positive and negative contribution. While I am able to get this graphically using the force plot, I need a way to get the top 3 features in an array or DataFrame. Is there an easy way to do this.

For example ;
I was wondering if there was a way to get the top 3 features that contribute positively and negatively (Higher and lower) )to the SHAP value in my example

# plot the SHAP values for the 0th observation 

![image](https://user-images.githubusercontent.com/34924403/95772092-2cb4d200-0c8a-11eb-8380-45d916d6caa6.png)

1.  SCodR_D' helps push the value to the right
2. SCfL_M, ZofC_H ,No_transactions push in the other direction

I need these features as an array or a dataframe so I can preform further operations on them

**Comment by thatlittleboy** [comment] 2023-07-21 00:48
close as duplicate of #1521

**Closed as not planned** 2023-07-21 00:48 UTC
