### ISSUE TITLE
[Feature Request?] Compatibility with Voting Classifiers

### ISSUE THREAD

**Issue by haoyu-jia** [shap/shap#2143] opened 2021-08-17 19:04 UTC
Not sure if this is already implemented or if I'm missing something, but it seems like shap doesn't support voting classifiers from sklearn.

Tried using TreeExplainer for it and got this:

/usr/local/lib/python3.7/dist-packages/shap/explainers/_tree.py in __init__(self, model, data, data_missing, model_output)
    975             self.base_offset = model.init_params[param_idx]
    976         else:
--> 977             raise Exception("Model type not yet supported by TreeExplainer: " + str(type(model)))
    978 
    979         # build a dense numpy version of all the tree objects

Exception: Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._voting.VotingClassifier'>

**Comment by Rithikmathur** [comment] 2023-04-27 13:34
Is it that shap does not work with voting classifier, I am trying to apply it but only getting error.

TypeError: The passed model is not callable and cannot be analyzed directly with the given masker! Model: VotingClassifier(estimators)

could you please help me resolve it?

**Comment by thatlittleboy** [comment] 2023-07-23 14:15
Closing as duplicate of #2908 . Let's track the feature request there.

**Closed as not planned by thatlittleboy** 2023-07-23 14:15 UTC
Labels: duplicate
