### ISSUE TITLE
ENH: Categorical feature not working with `shap.plots.scatter`

### ISSUE THREAD

**Issue by danieleongari** [shap/shap#3135] opened 2023-07-25 09:56 UTC
### Issue Description

When having a categorical feature, the scatter plot fails:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File [c:\users\onga1340\main\programs\adex_app\adex\utils.py:156](file:///C:/users/onga1340/main/programs/adex_app/adex/utils.py:156), in plot_shap(adex_object, explanation, plot, max_scatter)
    155 try:
--> 156     shap.plots.scatter(explanation[:,feature,itarget], color=explanation[:,feature,itarget])
    157 except TypeError:

File [c:\ProgramData\Miniconda3\envs\adex310\lib\site-packages\shap\plots\_scatter.py:195](file:///C:/ProgramData/Miniconda3/envs/adex310/lib/site-packages/shap/plots/_scatter.py:195), in scatter(shap_values, color, hist, axis_color, cmap, dot_size, x_jitter, alpha, title, xmin, xmax, ymin, ymax, overlay, ax, ylabel, show)
    194 for i in range(1,len(vals)):
--> 195     d = vals[i] - vals[i-1]
    196     if d > 1e-8 and d < min_dist:

TypeError: unsupported operand type(s) for -: 'str' and 'str'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 plot_shap(ao, explanation=e, plot=['scatter'], max_scatter=None)
      2 # NOTE: still not working for categorical variables

File [c:\users\onga1340\main\programs\adex_app\adex\utils.py:158](file:///C:/users/onga1340/main/programs/adex_app/adex/utils.py:158), in plot_shap(adex_object, explanation, plot, max_scatter)
    156             shap.plots.scatter(explanation[:,feature,itarget], color=explanation[:,feature,itarget])
    157         except TypeError:
--> 158             shap.plots.scatter(explanation[:,feature,itarget], color="#1E88E5")
    159             #pass # TODO: can not print categorical data!
    161 if 'summary_bar_plotly' in plot:

File [c:\ProgramData\Miniconda3\envs\adex310\lib\site-packages\shap\plots\_scatter.py:195](file:///C:/ProgramData/Miniconda3/envs/adex310/lib/site-packages/shap/plots/_scatter.py:195), in scatter(shap_values, color, hist, axis_color, cmap, dot_size, x_jitter, alpha, title, xmin, xmax, ymin, ymax, overlay, ax, ylabel, show)
    193 min_dist = np.inf
    194 for i in range(1,len(vals)):
--> 195     d = vals[i] - vals[i-1]
    196     if d > 1e-8 and d < min_dist:
    197         min_dist = d

TypeError: unsupported operand type(s) for -: 'str' and 'str'
```
The problem is that `vals` (i.e., the feature array) is of dtype object.

### Minimal Reproducible Example

```python
# X is a DataFrame with categorical column "catfeature"
explanation = explainer(X)
shap.plots.scatter(explanation[:,catfeature])
```

### Expected Behavior

Quick solution: raise a `NotImplementedError` if the vector is of dtype == object
Long solution: map each feature level to a number, execute the code, show the levels on the x-axis of the plot.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.1

**Comment by connortann** [comment] 2023-07-30 22:58
I've relabelled this issue as an Enhancement request rather than a bug, as presently the Scatter plot is not intended to work with categorical variables.

One could encode the categorical value as a number before plotting, for example with `pandas.factorize`. Or, if the categorical variable is Ordinal (has an underlying order), then perhaps you might want to manually map each category to a number.

Fundamentally though, I don't think it conceptually makes sense to use a scatter plot with a categorical variable. By definition, a scatter plot is a plot of two continuous variables. Would a `bar` or `violin` plot be more appropriate?

**Comment by thatlittleboy** [comment] 2023-08-20 10:07
I'm assuming the request is asking for something like this, right? So the x-axis is categorical.

![image](https://github.com/shap/shap/assets/30731072/7457825f-8d64-4df0-9c1e-8c0476606684)

Taken from: 
https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/scatter.html

But I don't think this notebook is reproducible, I took a look at the commit from which this notebook was committed (79354776372e6add7f495fbaf4c660dc4f771de6), but the offending line is there as well

https://github.com/shap/shap/blob/79354776372e6add7f495fbaf4c660dc4f771de6/shap/plots/_scatter.py#L185-L190

**Comment by dsgibbons** [comment] 2023-08-21 05:56
>  Would a `bar` or `violin` plot be more appropriate?

I think we need to plot all the points so we can enable color overlays (see the use of `scatter` in the README). `violin` won't plot all of the points. I think the chart found by @thatlittleboy's is probably better, but would be a bit of work to implement.

**Comment by thatlittleboy** [comment] 2023-08-21 17:29
This image came from the example notebook itself, so it was definitely implemented at some point (I'm assuming Scott didn't push up the relevant code / it wasn't merged in / it was from an earlier code state before https://github.com/shap/shap/commit/79354776372e6add7f495fbaf4c660dc4f771de6).

If we can confirm that the image is the desired output in the request, I think we should be able to make it happen

**Comment by danieleongari** [comment] 2023-08-23 06:08
Thanks @thatlittleboy, the figure you presented is a very nice representation of the scatter plot for categorical features: indeed, it makes sense to spread the points such that the user can better appreciate their value and density.
I marked this initially as "bug" because the old scatter API, i.e., not using the Explanation object, does work with categorical, even if the scatter plot is very simple (i.e., keeping the markers of each categorical level aligned) but at least it does not break the code with an error.

**Comment by hypostulate** [comment] 2024-02-16 14:35
Ran into the same issue this morning. I found that if you are using true "Categorical" dtypes with `pandas`, a single line change will fix the plot:

```
# d = vals[i] - vals[i-1]
d = 2  # Any value to set the jitter width
```

**Comment by mattharrison** [comment] 2024-06-20 20:32
Is there any update on this, @slundberg ? The documentation hints that categorical scatter plots work, yet I can't get them to work.

**Closed as completed** 2024-08-20 08:03 UTC
Labels: enhancement, visualization
