### ISSUE TITLE
There was an error when using Pyinstaller to package a program that includes SHAP

### ISSUE THREAD

**Issue by leeprinxin** [shap/shap#2910] opened 2023-05-03 08:50 UTC
I need to convert my program to an executable file using pyinstaller, but when I run the converted exe file, I encounter the following error: FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\xin\Documents\GitHub\ChillerWater\dist\api_fast\Library\bin' [21632] Failed to execute script 'api_fast' due to an unhandled exception!
`Traceback (most recent call last):
  File "api_fast.py", line 8, in <module>
    from lib import tools as tool
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "lib\tools.py", line 7, in <module>
    import shap
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "shap\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "shap\_explanation.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "shap\utils\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "shap\utils\_clustering.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "numba\__init__.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "numba\core\config.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "llvmlite\binding\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "llvmlite\binding\dylib.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "llvmlite\binding\ffi.py", line 162, in <module>
  File "os.py", line 1111, in add_dll_directory
FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'C:\\Users\\xin\\Documents\\GitHub\\ChillerWater\\dist\\api_fast\\Library\\bin'
[21632] Failed to execute script 'api_fast' due to unhandled exception!`
The issue is caused by the shap package I have installed. I have seen other users with the [same problem,](https://github.com/slundberg/shap/issues/2439)  in the discussion thread but there is currently no solution available

**Comment by dsgibbons** [comment] 2023-06-16 23:20
Closing, as this is a duplicate of #2439

**Closed as completed by dsgibbons** 2023-06-16 23:20 UTC
