### ISSUE TITLE
show=False causes error in shap.plots.waterfall

### ISSUE THREAD

**Issue by jfkingiii** [shap/shap#2307] opened 2021-12-07 00:41 UTC
```
import xgboost
import shap

# train XGBoost model
X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

shap.plots.waterfall(shap_values[0], show=False)
```
```
shap.plots.waterfall(shap_values[0], show=False)
Traceback (most recent call last):

  File "C:\Users\jfking\AppData\Local\Temp/ipykernel_8892/1156395074.py", line 1, in <module>
    shap.plots.waterfall(shap_values[0], show=False)

  File "C:\Users\jfking\Anaconda3\lib\site-packages\shap\plots\_waterfall.py", line 43, in waterfall
    plt.ioff()
```

 `matplotlib.pyplot` is imported as `pl` at the start of `_waterfall.py`:
```
try:
    import matplotlib.pyplot as pl
    import matplotlib
except ImportError:
    warnings.warn("matplotlib could not be loaded!")
    pass
```

**Comment by areeh** [comment] 2021-12-13 15:45
duplicate of #2261

**Closed as completed** 2023-06-03 09:44 UTC
