### ISSUE TITLE
show = False has no effect with interactions

### ISSUE THREAD

**Issue by BrianMiner** [shap/shap#252] opened 2018-09-03 01:47 UTC
Hello  Scott

While show=False works without interaction Shapley Values, it appears to fail (no effect) when using interactions such as:

`shap.dependence_plot(("Age", "Age"),shap_values, toScore,show=False)`

**Comment by slundberg** [comment] 2018-09-05 23:41
Strange since `pl.show()` is only called when `show=True`:
https://github.com/slundberg/shap/blob/ed284b6278813c5292d83dc2a22976a0fdedd4ec/shap/plots/dependence.py#L91-L93

**Comment by thatlittleboy** [comment] 2023-06-25 04:43
Closing due to staleness, please feel free to open a new issue with reproducible example if needed.

**Closed as not planned** 2023-06-25 04:43 UTC
