### ISSUE TITLE
One more: DeepExplainer - TypeError: Fetch argument None has invalid type <type 'NoneType'>

### ISSUE THREAD

**Issue by hcthorsen** [shap/shap#496] opened 2019-03-17 08:29 UTC
I have a problem similar to #324. 

My model looks like this:

![image](https://user-images.githubusercontent.com/30860976/54473861-bca84680-47dd-11e9-8a4f-197a0ad94e01.png)

Sorry, I'm working on a secure server, so I'm not able to copy text, so I have to show screenshots instead.

When I try to run DeepExplainer I get the following error:

![image](https://user-images.githubusercontent.com/30860976/54473884-0a24b380-47de-11e9-9e36-bf644718ef9c.png)

I tried to print self.phi_symbolics[i] and got: [None]

Any ideas on how to debug this?
I'm using Keras 2.1.6, Tensorflow 1.5.0 and Shap 0.23.1

**Comment by keithmattix** [comment] 2019-03-28 21:26
I'm having the same issue :(

**Comment by slundberg** [comment] 2019-03-28 21:46
If you can post a self-contained example notebook that demonstrates the problem then I can take a look. Just based on the error messages it is really hard to say anything. You can also try GradientExplainer and see if it works or has a similar issue.

**Comment by keithmattix** [comment] 2019-03-28 21:59
I'll get on that, but in the meantime, I found a similar issue with DeepExplain: [](https://github.com/marcoancona/DeepExplain/issues/28). The issue I think is with `tf.gradients` returning None values for Embedding layers

**Comment by keithmattix** [comment] 2019-03-28 22:02
Ah here's the reason I think: [keras issue #12270](https://github.com/keras-team/keras/issues/12270#issuecomment-465309599)

**Comment by slundberg** [comment] 2019-03-28 22:06
Ah yes. There is no gradient back to the index used to select the embedding vector. You can get around that by just summing up all the credit assigned to each embedding vector, but that requires you to use the embedding vectors as the input for GradientExplainer...which is a pain. This could be fixed by overriding the gradient operator as we do in DeepExplainer...but that's a todo.

**Comment by keithmattix** [comment] 2019-03-28 22:16
I may have misunderstood, but if the gradient operator is overridden in `DeepExplainer` (which is where this error is occurring, how would overriding it on our end fix the problem? Also, is there anything in the documentation that could further explain a workaround? If not, I can submit a PR if/when I find one :)

**Comment by slundberg** [comment] 2019-03-28 22:23
Overridding it is needed in order to pass credit back through a non-differential function (in this case an index lookup). This is a change that needs to happen inside the GradientExplainer code to support embedding layers.

The issue with DeepExplainer is a separate issue. Hence why a self-contained example will help debug it.

**Comment by hcthorsen** [comment] 2019-04-01 08:23
I'll try to make a notebook example, but I have a more urgent deadline.

**Comment by andriy-nikolov** [comment] 2019-04-09 11:41
I encountered a similar problem when using the `tensorflow.keras` packages, but interestingly it does not occur when using native `keras`. I managed to reproduce it with keras 2.2.4, tensorflow 1.12, and shap 0.27.0 by slightly modifying the IMDB example from the notebooks.
The version in imdb_example_func_native.py using `keras` works, but the same version using `tensorflow.keras` throws the "TypeError: Fetch argument None has invalid type <type 'NoneType'>".
The issue seems to occur because `keras` uses the `GatherV2` operation type for the embedding lookup, while `tensorflow.keras` uses `ResourceGather`. Managed to overcome by registering the `gather` function as an op handler for `ResourceGather` in deep_tf.py.

[imdb_example_func_tf.py.txt](https://github.com/slundberg/shap/files/3058703/imdb_example_func_tf.py.txt)
[imdb_example_func_native.py.txt](https://github.com/slundberg/shap/files/3058704/imdb_example_func_native.py.txt)

**Comment by andriy-nikolov** [comment] 2019-04-09 11:56
Not sure if this is a root cause, but added a PR, just in case if it's relevant: https://github.com/slundberg/shap/pull/540

**Comment by akshayuppal3** [comment] 2019-06-14 17:50
I am still facing the same error.
for this model
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_12 (InputLayer)           (None, 150, 18, 10)  0                                            
__________________________________________________________________________________________________
input_11 (InputLayer)           (None, 150, 18)      0                                            
__________________________________________________________________________________________________
reshape_23 (Reshape)            (None, 2700, 10)     0           input_12[0][0]                   
__________________________________________________________________________________________________
reshape_21 (Reshape)            (None, 2700)         0           input_11[0][0]                   
__________________________________________________________________________________________________
time_distributed_16 (TimeDistri (None, 2700, 10, 10) 1070        reshape_23[0][0]                 
__________________________________________________________________________________________________
embedding_11 (Embedding)        (None, 2700, 300)    18046800    reshape_21[0][0]                 
__________________________________________________________________________________________________
time_distributed_17 (TimeDistri (None, 2700, 60)     17040       time_distributed_16[0][0]        
__________________________________________________________________________________________________
reshape_22 (Reshape)            (None, 150, 5400)    0           embedding_11[0][0]               
__________________________________________________________________________________________________
reshape_24 (Reshape)            (None, 150, 1080)    0           time_distributed_17[0][0]        
__________________________________________________________________________________________________
masking_11 (Masking)            (None, 150, 5400)    0           reshape_22[0][0]                 
__________________________________________________________________________________________________
masking_12 (Masking)            (None, 150, 1080)    0           reshape_24[0][0]                 
__________________________________________________________________________________________________
concatenate_6 (Concatenate)     (None, 150, 6480)    0           masking_11[0][0]                 
                                                                 masking_12[0][0]                 
__________________________________________________________________________________________________
bidirectional_11 (Bidirectional (None, 150, 240)     6336960     concatenate_6[0][0]              
__________________________________________________________________________________________________
bidirectional_12 (Bidirectional (None, 150, 240)     346560      bidirectional_11[0][0]           
__________________________________________________________________________________________________
time_distributed_18 (TimeDistri (None, 150, 100)     24100       bidirectional_12[0][0]           
__________________________________________________________________________________________________
crf_6 (CRF)                     (None, 150, 2)       210         time_distributed_18[0][0]        
__________________________________________________________________________________________________
dense_layer (Dense)             (None, 150, 1)       3           crf_6[0][0]                      
__________________________________________________________________________________________________
lambda_13 (Lambda)              (None, 150, 1)       0           dense_layer[0][0]                
__________________________________________________________________________________________________
reshape_last (Reshape)          (None, 150)          0           lambda_13[0][0]                  
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 150)          22650       reshape_last[0][0]               
==================================================================================================
Total params: 24,795,393
Trainable params: 22,653
Non-trainable params: 24,772,740
__________________________________________________

**Comment by akshayuppal3** [comment] 2019-06-14 18:14
I am still getting the error with my model while using deep explainer...
![image](https://user-images.githubusercontent.com/25509837/59529297-454e8580-8ea6-11e9-9271-f91a7a73e37a.png)

**Comment by slundberg** [comment] 2019-06-18 23:04
@akshayuppal3 what version are you running of shap and your modeling package (Keras?).

**Comment by akshayuppal3** [comment] 2019-06-19 14:48
I am using 2.2.4

**Comment by akshayuppal3** [comment] 2019-06-19 20:21
what is the correct version?

**Closed as completed** 2019-06-19 20:20 UTC
Labels: todo

**Comment by slundberg** [comment] 2019-06-19 20:22
@akshayuppal3 I think this was caused by a recent update in tensorflow that stopped our workaround for back propagating through embedding layers from working. I just pushed a commit that fixed a similar issue I found when using TF 1.14 and Keras 2.2.4

**Comment by akshayuppal3** [comment] 2019-06-19 20:24
Thanks
