### ISSUE TITLE
`beeswarm` corrupts `Explanation` object

### ISSUE THREAD

**Issue by ravwojdyla** [shap/shap#2240] opened 2021-10-27 22:27 UTC
Reproduction:

```python
import xgboost
import shap

X, y = shap.datasets.boston()
model = xgboost.XGBRegressor().fit(X, y)
explainer = shap.Explainer(model)
shap_values = explainer(X)
```

First see the valid summary:

```python
shap.summary_plot(shap_values, max_display=10)
```
![image](https://user-images.githubusercontent.com/1419010/139154104-630ca326-d297-4b10-8418-669a1205253a.png)

Now use beeswarm with truncated list:

```python
shap.plots.beeswarm(shap_values, max_display=2)
```
![image](https://user-images.githubusercontent.com/1419010/139154283-de7c6e4f-6073-47c7-8c1e-cbd6f2475af8.png)

Now the summary graph is corrupted:

```python
shap.summary_plot(shap_values, max_display=10)
```
![image](https://user-images.githubusercontent.com/1419010/139154248-60a74e68-0d41-4772-af41-e7853776e541.png)

Notice how the 2nd row (sum of features) corrupted the summary plot ^

**Comment by AlexTo** [comment] 2021-11-22 06:08
I can confirm that beeswarm function changes the `shap.values` array.

**Comment by js850** [comment] 2022-01-10 20:28
I have also noticed this.  A little debugging shows it's happening in these lines in _beeswarm.py

```python
    # see how many individual (vs. grouped at the end) features we are plotting
    if num_features < len(values[0]):
        num_cut = np.sum([len(orig_inds[feature_order[i]]) for i in range(num_features-1, len(values[0]))])
        values[:,feature_order[num_features-1]] = np.sum([values[:,feature_order[i]] for i in range(num_features-1, len(values[0]))], 0)
```

A workaround is to use `copy.deepcopy(shap_values)` before passing them into `beeswarm`

**Comment by thatlittleboy** [comment] 2023-07-03 01:05
Closing, also duplicate of #1970

**Closed as completed** 2023-07-03 01:05 UTC
