### ISSUE TITLE
BUG: Tests fail on MacOX 

### ISSUE THREAD

**Issue by connortann** [shap/shap#3032] opened 2023-06-23 13:12 UTC
Tests fail when run on MacOX runners, as per #3029 

EDIT: lightgbm issue resolved, now getting a pytorch error:

```
=========================== short test summary info ============================
ERROR  - OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib, 0x000A): Library not loaded: '@loader_path/../../functorch/.dylibs/libiomp5.dylib'
  Referenced from: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib'
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/../../functorch/.dylibs/libiomp5.dylib' (no such file), '/usr/lib/libiomp5.dylib' (no such file)
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by thatlittleboy** [comment] 2023-06-23 14:20
@connortann I can take this, I've reproduced this locally.

**Comment by connortann** [comment] 2023-06-23 17:05
Reopening as macos tests still fail on #3029 , for what now seems to be a pytorch issue

**Comment by thatlittleboy** [comment] 2023-06-23 18:50
I'll see what I can do tmr, torch tests are a little tricky for me to debug because i dont have cuda on my macbook

**Comment by thatlittleboy** [comment] 2023-06-24 04:12
@connortann MacOS Tests are passing now. I just cleared the Cache for MacOS under `Actions` and reran tests.

**Comment by thatlittleboy** [comment] 2023-06-24 18:48
Unfortunately it seems like the bug is still present. Now that #3029 was merged, the subsequent PR CI runs are all failing on MacOS, see e.g. https://github.com/slundberg/shap/actions/runs/5365701428/jobs/9734686072?pr=3040

```
ERROR  - OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib, 0x000A): Library not loaded: '@loader_path/../../functorch/.dylibs/libiomp5.dylib'
  Referenced from: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/libtorch_global_deps.dylib'
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/lib/../../functorch/.dylibs/libiomp5.dylib' (no such file), '/usr/lib/libiomp5.dylib' (no such file)
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 28.54s ===============================

```

Even after manually deleting the MacOS cache in the Actions tab.

**Comment by connortann** [comment] 2023-06-24 21:38
Could a short-term patch be to only run 'core' tests on Mac?

**Comment by thatlittleboy** [comment] 2023-06-25 09:37
@connortann I pushed up what I think is the fix in #3041 , please take a look when you have the time. I've confirmed that the test CI passes while reading `torch` from the cache.

![image](https://github.com/slundberg/shap/assets/30731072/765941dd-a629-4da4-ab51-743648601dd6)

**Comment by connortann** [comment] 2023-06-25 11:49
That looks sensible, approved - good to merge on the rebased checks pass.

The tests still take a long time on macos as you observed. I suppose it's not necessarily a big deal, as PRs can still be merged before non-required checks pass.

Longer term, it would be great to work towards a much faster CI suite- ideally, low single digit minutes!

**Comment by connortann** [comment] 2023-07-15 11:52
@thatlittleboy  I'm seeing this issue crop up again unforunately:
https://github.com/slundberg/shap/actions/runs/5561868125/jobs/10160081638

**Comment by thatlittleboy** [comment] 2023-07-15 14:23
@connortann Tests are failing on MacOS but it's a different problem altogether. I believe it's because lightgbm made a 4.0 release two days ago, it's probably related to that.

I'll close this for now and open another issue to track this problem.

**Closed as completed by thatlittleboy** 2023-07-15 14:23 UTC
Labels: bug, ci
