### ISSUE TITLE
top n_features extraction / UnboundLocalError

### ISSUE THREAD

**Issue by diordanovitch** [shap/shap#185] opened 2018-07-27 14:45 UTC
Hi Scott. Thanks for your work, it’s just awesome.

I have 2 questions.

First, is there a method to extract the top_n features according to their shap_values ? It’s would be very useful to use them further in the code (especially in my case when I use some feature selection which is not totally stable, and so features positions can change).

Second question, when I try to plot the bars (shap.summary_plot(shap_values, train_features, plot_type=”bar”) ), it returns this message : “ UnboundLocalError: local variable ‘vmin’ referenced before assignment. ” And no plot.
I searched in the code (plots.py) and did not find the solution.

Thanks again,
Dimitri

**Comment by slundberg** [comment] 2018-07-27 16:03
Thanks. For the top_n features I would suggest using the average magnitude of the SHAP values over all the samples `np.argsort(-np.abs(shap_values).mean(0))[:N]`.

For the summary plot that looks like a bug, but I can't reproduce it on my end. Could you post complete example that creates the problem for you?

**Comment by diordanovitch** [comment] 2018-08-07 12:29
Thanks for your answer. `np.argsort(-np.abs(shap_values).mean(0))[:N]` is just what I was looking for.

For the summary plot, I can give you my code, but it is totally normal I think, and the other plots work well.


```
`xgtrain = xg.DMatrix(train_features, train_labels)
xgtest = xg.DMatrix(test_features, test_labels)


#true param
params = {
    'max_depth':7,
    'min_child_weight': 1,
    'eta':0.01,
    'subsample': 0.9,
    'colsample_bytree': 0.8,
    'objective':'binary:logistic',
    'eval_metric':'auc'
}

best_model = xg.train(
    params,
    xgtrain,
    num_boost_round=1814,
    evals=[(xgtest, "Test")])



import shap
shap.initjs()

explainer = shap.TreeExplainer(best_model)
shap_values = explainer.shap_values(train_features)

shap.summary_plot(shap_values, train_features, plot_type="bar")
```
`


-> UnboundLocalError: local variable 'vmin' referenced before assignment

**Comment by slundberg** [comment] 2018-08-08 23:58
I just fixed a problem with the bar plot that will be in 0.22.3 let me know if this fixes your issue as well.

**Closed as completed** 2023-07-19 15:26 UTC
