### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 337: invalid start byte

### ISSUE THREAD

**Issue by Allenhuang0708** [shap/shap#1864] opened 2021-03-08 08:04 UTC
Hi, my envs as follow:
xgboost                    1.3.3
shap                       0.38.1
python  3.7.7
When I am running my program, there came a issue when decoding, I printed out my model.get_booster().save_raw(), it's like this:
`bytearray(b'binfn\xac\xedA\x08\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00reg:squarederror\x06\x00\x00\x00\x00\x00\x00\x00gbtree\x0f\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...') (I deleted the last characters)`

I noticed that we have already lstrip 'binf' but i guess the problem came out of the 'n\xac\xedA' part, cause when I printed out the base score etc, the number is clearly wrong:
`base 5.835820683183942e-34 num features 0 num class 16777216 extra attrs 0 eval metrics 16777216`

The orginial base score by the model is: 29.709193548387095

I  am wondering why is this happend? The xgboost saved the model in an unregular way?

By the way, we are using xgboost regession model

**Comment by Allenhuang0708** [comment] 2021-03-09 09:46
A related decoding issue is on #1215
But my issue is not the same with this one, I checked and printed out the decoded value for the base score, number of features etc, they are not the same with the model originial values before saving.

So I am very curious how did the xgbt regression model save the raw fitted model?
@slundberg

**Comment by stang2424** [comment] 2021-09-01 21:27
One of my co-workers found the problem.

In XGBTreeModelLoader,

`self.buf` = xgb_model.save_raw().lstrip(b'binf') `

doesn't quite work properly. lstrip continues to strip ALL instances of 'b', 'i', 'n', 'f' until a non 'b' 'i' 'n' 'f' character shows up; that's just what lstrip does. Most of the time, most XGBoost buffers start with 'binf', and all seems well. (So, probably 99% of the time, the lstrip solution seems to work). However, the problem arises that some perfectly valid XGBoost buffers start with 'binfn', or 'binff', or 'binfb', or 'binfi'. Note the extra 'n' or extra 'f'. Just like in the original authors example, the buffer started with 'binfn'. The extra 'n' or 'f' is just a part of the representation of the base score (the valid start of the XGBoost buffer representation). lstrip will strip this second 'n' or 'f', which is crucially stripping a valid part of the buffer. **Ultimately, lstrip is not the correct approach for simply removing the first instance of 'binf', since lstrip intended for more general stripping purposes.**

I suppose this was tricky since .lstrip('binf') looks like it should be correct, but it is capable of stripping more characters than is intended. The issue is further trickier to track down because the code **appears** to parse information about the XGBoost model, but as noted, the base scores and other values are all seemingly wrong and nonsense. The numbers get parsed in, and no error message pops up. The UTF-8 Encoding error happens later, which is sort of a mis-direction error that makes it hard to understand the bug, since the typical "fixes" for UTF-8 encoding errors happen in different places.

**Comment by CloseChoice** [comment] 2024-01-24 20:59
Should be fixed via #3345. If any other issues arise with serializing/deserializing feel free to open a new issue.

**Closed as completed by CloseChoice** 2024-01-24 20:59 UTC
Labels: todo
