### ISSUE TITLE
Exception in KernelExplainer.solve()

### ISSUE THREAD

**Issue by paramdutta** [shap/shap#2] opened 2017-09-21 22:58 UTC
Hi,
Thanks for you work. I have used DeepLift and I am trying out this approach.

I have a feed forward neural network built using Keras. All features in my dataset are continuous. There are 31 features. I setup up the python program just like the KNN example on github landing page.

I get the following  error. Let me know if I am doing anything wrong that is triggering this.

Thanks
Param

Error:
IndexError                                Traceback (most recent call last)
<ipython-input-44-50aa4f6f173f> in <module>()
     26 print(x.shape)
     27 print(x)
---> 28 visualize(explainer.explain(x))

/Library/Python/2.7/site-packages/shap/shap.pyc in explain(self, incoming_instance, **kwargs)
    169 
    170         # solve then expand the feature importance (Shapley value) vector to contain the non-varying features
--> 171         vphi,vphi_var = self.solve(self.nsamples/self.max_samples)
    172         phi = np.zeros(len(self.data.groups))
    173         phi[self.varyingInds] = vphi

/Library/Python/2.7/site-packages/shap/shap.pyc in solve(self, fraction_evaluated)
    324         #nonzero_inds = np.arange(self.M)
    325 
--> 326         eyAdj2 = eyAdj - self.maskMatrix[:,nonzero_inds[-1]]*(self.link.f(self.fx) - self.link.f(self.fnull))
    327         etmp = np.transpose(np.transpose(self.maskMatrix[:,nonzero_inds[:-1]]) - self.maskMatrix[:,nonzero_inds[-1]])
    328         #print(self.maskMatrix)

IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by slundberg** [comment] 2017-09-25 05:50
It looks like it might have selected an all-zero explanation and then failed. I'll look into it and try and reproduce the problem. Thanks for letting me know!

**Comment by paramdutta** [comment] 2017-10-03 21:11
Thanks. Can you give me some clues that I can try to fix the problem?

-Param

**Comment by slundberg** [comment] 2017-10-04 19:54
I just pushed changes that should fix the problem. It showed up when the feature selection phase found no important features. So the fix just returns a zero explanation in that case.

You can also turn off feature selection by passing `KernelExplainer` the param `use_l1=False`, then the regression estimation will assume all features have non-zero impact and not do debiasing feature selection. You can also increase the number of samples with the `nsamples` param.

**Comment by slundberg** [comment] 2017-10-09 17:09
Closing this issue unless I hear otherwise.

**Closed as completed by slundberg** 2017-10-09 17:09 UTC
