### ISSUE TITLE
beeswarm_plot issue with variable usage

### ISSUE THREAD

**Issue by GhadaElkhawaga** [shap/shap#1590] opened 2020-11-16 08:11 UTC
**while using 'beeswarm' plot... I got the following error:**

/usr/local/lib/python3.6/dist-packages/shap/plots/_beeswarm.py in beeswarm(shap_values, max_display, order, clustering, cluster_threshold, color, axis_color, alpha, show, log_scale, color_bar, plot_size, color_bar_label)
     55         #     out_names = shap_exp.output_names
     56 
---> 57     order = convert_ordering(order, values)
     58 
     59 

UnboundLocalError: local variable 'values' referenced before assignment
-----------------------------------------------------------------------------------------------

**and here is my code which produced the aforementioned error:**
``print('summary plot of shap values - normal')
    shap.plots.beeswarm(shap_values, show=False)
    # plt.savefig('Shap values_normal_%s_%s_%s_%s.png'%(typ, dataset_name, cls_method, method_name), dpi=300, bbox_inches='tight');
    plt.savefig(os.path.join(shap_values_dir,
                             'Shap values_normal_%s_%s_%s_%s.png' % (typ, dataset_name, cls_method, method_name)),
                dpi=300, bbox_inches='tight');
    plt.clf()
    plt.close()

**Comment by chrislill** [comment] 2021-02-17 15:04
@xingbow explains this issue in #1460. The fix is to send an explanation object to the beeswarm plot, rather than a numpy array of shap values.

**Comment by thatlittleboy** [comment] 2023-06-20 15:59
Closing as duplicate of #1460

**Closed as completed by thatlittleboy** 2023-06-20 15:59 UTC
