### ISSUE TITLE
swarm plot and barplot do not match

### ISSUE THREAD

**Issue by yudeng2015** [shap/shap#2753] opened 2022-11-06 04:35 UTC
Hi 
I passed the same shap_value for swarm plot and bar plot. However, these two plots show different features. The feature set is off by one. Here is the code I used. Is this normal? 
```
import shap # scale 
explainer = shap.Explainer(clf, preprocessing.scale(X_train) , feature_names=vectorizer.get_feature_names() )
shap_values = explainer(preprocessing.scale(X_train))
shap.plots.beeswarm(shap_values)
shap.plots.bar(shap_values)
```
I attached the result plots here 
<img width="961" alt="Screen Shot 2022-11-05 at 11 32 53 PM" src="https://user-images.githubusercontent.com/83092124/200154395-4f758be7-51a4-43d9-919f-71e46d9f0c3c.png">

As you can see, feature C0262963 did not appear in swarm plot but it shows up in bar plot

**Comment by AzaelCC** [comment] 2023-04-17 23:17
I'm having the same problem. Where you able to fix it?

**Comment by yudeng2022** [comment] 2023-04-18 00:43
Yes, when I call shap.plot.beeswarm(shap_values), it modified the value of shape_values somehow. So when I call shap.plot.bar(shap_values), it gave a different result. Try to use shap_values.copy() instead of shap_values, see if it makes a difference for you.

**Comment by thatlittleboy** [comment] 2023-07-03 00:59
Closing as duplicate of #1970.

**Closed as completed** 2023-07-03 00:59 UTC
Labels: bug
