### ISSUE TITLE
NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by billy-odera** [shap/shap#603] opened 2019-05-22 15:19 UTC
I am running my lightGBM model
```
%%time
y_pred_lgb = np.zeros(len(test_X))
num_round = 1000000
for fold_n, (train_index, valid_index) in enumerate(folds.split(train_X,train_Y)):
    print('Fold', fold_n, 'started at', time.ctime())
    X_train, X_valid = train_X.iloc[train_index], train_X.iloc[valid_index]
    y_train, y_valid = train_Y.iloc[train_index], train_Y.iloc[valid_index]
    
    train_data = lgb.Dataset(X_train, label=y_train)
    valid_data = lgb.Dataset(X_valid, label=y_valid)
        
    model = lgb.train(params,train_data,num_round,#change 20 to 2000
                    valid_sets = [train_data, valid_data],verbose_eval=1000,early_stopping_rounds = 3500)##change 10 to 200
            
    y_pred_lgb += model.predict(test_X, num_iteration=model.best_iteration)/5
```

when I create a tree explainer as below
`explainer = shap.TreeExplainer(model)`

I get the error **NameError: name 'model' is not defined**

**Comment by detrin** [comment] 2023-08-26 09:35
@billy-odera Seems to me that this is an issue on the side of your code. Make sure that after loop the `model` object still exists.

@thatlittleboy Maybe a candidate for closing?

**Comment by thatlittleboy** [comment] 2023-08-26 10:22
@billy-odera I'll close this issue for now due to staleness, feel free to respond here with an updated reproducible example and I'll be happy to reopen the issue.

**Closed as not planned by thatlittleboy** 2023-08-26 10:22 UTC
