### ISSUE TITLE
problem with pytorch model

### ISSUE THREAD

**Issue by eranbio** [shap/shap#477] opened 2019-03-05 14:17 UTC
I am trying to use shap to interpret genomic deep learning model in PyTorch. The input tensors to shap are three dimensional and have shapes like torch.Size([100, 4, 2000]) for the background and 
torch.Size([5, 4, 2000]) for the input samples for shap_values().

I get the following error message:

  File "/home/users/bioinf/erane/work/unity/tools/gedai/dna_pytorch_shap.py", line 668, in <module>
    main()
  File "/home/users/bioinf/erane/work/unity/tools/gedai/dna_pytorch_shap.py", line 215, in main
    shap_values = e.shap_values(xdata)
  File "/evogene/software/anaconda3/envs/py3.6-env-erane/lib/python3.6/site-packages/shap/explainers/deep/__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "/evogene/software/anaconda3/envs/py3.6-env-erane/lib/python3.6/site-packages/shap/explainers/deep/deep_pytorch.py", line 221, in shap_values
    sample_phis = self.gradient(feature_ind, joint_x)
  File "/evogene/software/anaconda3/envs/py3.6-env-erane/lib/python3.6/site-packages/shap/explainers/deep/deep_pytorch.py", line 166, in gradient
    grads = [torch.autograd.grad(selected, x)[0].cpu().numpy() for x in X]
  File "/evogene/software/anaconda3/envs/py3.6-env-erane/lib/python3.6/site-packages/shap/explainers/deep/deep_pytorch.py", line 166, in <listcomp>
    grads = [torch.autograd.grad(selected, x)[0].cpu().numpy() for x in X]
  File "/evogene/software/anaconda3/envs/py3.6-env-erane/lib/python3.6/site-packages/torch/autograd/__init__.py", line 144, in grad
    inputs, allow_unused)
**RuntimeError: hook 'deeplift_grad' has changed the size of value**

On the same machine I can successfully use shap with examples of pytorch MNIST image classification code (like https://www.kaggle.com/ceshine/pytorch-deep-explainer-mnist-example) .  Any hint will be well appreciated. 

Eran

**Comment by slundberg** [comment] 2019-03-06 23:49
Do you get the same error for GradientExplainer as well?

**Comment by eranbio** [comment] 2019-03-10 20:21
I haven't tested my code with GradientExplainer yet. However I have some insight regarding the problem with DeepExplainer. After I isolated the components of my pytorch model, it turned out that the crash occurs in the Conv1d layer of my model. After changing tensor dimensions and using Conv2d instead, I was able to run shap and the results looks fine, although I got a warning message which I am not sure about. I will post it soon.

**Comment by eranbio** [comment] 2019-03-19 09:54
this is the warning message which I get:
Warning: unrecognized nn.Module: <class 'type'>

Scott, for your question - I don't get the same error with GradientExplainer. With GradientExplainer I can run with either Conv1d or Conv2d.  I also don't get the above warning.

**Comment by slundberg** [comment] 2019-03-20 01:03
Hmm... @gabrieltseng might have some ideas since he wrote the PyTorch parts.

**Comment by gabrieltseng** [comment] 2019-03-20 13:49
Hi!

With respect to the warning you are getting (Warning: unrecognized nn.Module: <class 'type'>), this is to tell you that Conv1d isn't implemented in the deep explainer yet. There was a typo in the warning, which has been fixed here: https://github.com/slundberg/shap/commit/714110b0eea969e78437771c50c29dc6cc486605

For the first error, could you send me the model you are using? Because Conv1d isn't implemented in the deep explainer, it should default to not changing the gradient.

Modifying one of the tests to include a conv1d layer does seem to work:
```python
def test_pytorch_regression():
    """Testing regressions (i.e. single outputs)
    """
    try:
        import torch
        from torch import nn
        from torch.nn import functional as F
        from torch.utils.data import TensorDataset, ConcatDataset, DataLoader
        from sklearn.datasets import load_boston
    except Exception as e:
        print("Skipping test_pytorch_regression!")
        return
    import shap

    X, y = load_boston(return_X_y=True)
    num_features = X.shape[1]
    data = TensorDataset(torch.tensor(X).float(),
                         torch.tensor(y).float())
    loader = DataLoader(data, batch_size=128)

    class Net(nn.Module):
        def __init__(self, num_features):
            super(Net, self).__init__()
            self.conv1d = nn.Conv1d(1, 1, 1)
            self.linear = nn.Linear(num_features, 1)

        def forward(self, X):
            return self.linear(self.conv1d(X.unsqueeze(1)).squeeze(1))
    model = Net(num_features)
    optimizer = torch.optim.Adam(model.parameters())

    def train(model, device, train_loader, optimizer, epoch):
        model.train()
        num_examples = 0
        for batch_idx, (data, target) in enumerate(train_loader):
            num_examples += target.shape[0]
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = F.mse_loss(output.squeeze(1), target)
            loss.backward()
            optimizer.step()
            if batch_idx % 2 == 0:
                print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(data), len(train_loader.dataset),
                           100. * batch_idx / len(train_loader), loss.item()))

    device = torch.device('cpu')
    train(model, device, loader, optimizer, 1)

    next_x, next_y = next(iter(loader))
    np.random.seed(0)
    inds = np.random.choice(next_x.shape[0], 20, replace=False)
    e = shap.DeepExplainer(model, next_x[inds, :])
    test_x, test_y = next(iter(loader))
    shap_values = e.shap_values(test_x[:1])

    model.eval()
    model.zero_grad()
    with torch.no_grad():
        diff = (model(test_x[:1]) - model(next_x[inds, :])).detach().numpy().mean(0)
    sums = np.array([shap_values[i].sum() for i in range(len(shap_values))])
    d = np.abs(sums - diff).sum()
    assert d / np.abs(diff).sum() < 0.001, "Sum of SHAP values does not match difference! %f" % (
            d / np.abs(diff).sum())
```

**Comment by eranbio** [comment] 2019-03-24 07:06
Hi Gabriel,
Sorry, I think I caused some confusions. I actually had the original error (RuntimeError: hook 'deeplift_grad' has changed the size of value) with the **Pool1d** layer. After moving to **Pool2d**, I could run successfully.
The warning( Warning: unrecognized nn.Module: <class 'type'>) is probably related to Conv1d.
So if I understand correctly Conv1d and Pool1d are not yet supported in DeeExplainer. Is there a plan to support them? Is there an updated list of all modules which are supported?
Thanks!
Eran

**Comment by gabrieltseng** [comment] 2019-03-24 19:06
Hi Eran,

With respect to the warning, it should be fixed by this pull request: https://github.com/slundberg/shap/pull/507 . However, since a conv layer is linear, the default behaviour of the deep explainer when it doesn't recognize the module (to just take the gradient as normally calculated by pytorch) is the correct one, so the results will be correct with a conv1d layer despite the warning.

You are right; there is a bug in the max pool 1d layer; thanks for spotting it! I will look into fixing it.

You can see which modules are explicitly supported here: https://github.com/slundberg/shap/blob/master/shap/explainers/deep/deep_pytorch.py#L313

Thanks,

Gabi

**Closed as completed** 2019-04-19 21:36 UTC

**Comment by austinmw** [comment] 2019-07-17 04:12
Hi, I'm wondering if it's safe to ignore this warning for the layer types `Flatten` and/or `AdaptiveAvgPool2d`? 
**Edit:** Oh also, what about resnet `BasicBlock`s?

**Comment by gabrieltseng** [comment] 2019-07-17 15:12
Hi!

1) A `Flatten` layer hasn't been implemented in PyTorch yet. Assuming the flatten layer looks something like what is being implemented here: https://github.com/pytorch/pytorch/pull/22245, then this doesn't affect the gradients - the DeepExplainer should work fine for this.

2) Support for Adaptive Average Pooling was added here: https://github.com/slundberg/shap/pull/609. However, the correct behaviour for the DeepExplainer for Adaptive Average Pooling layers is to leave the gradient unchanged, since it is linear. This is what the DeepExplainer does when it doesn't recognize a Module, so it should be safe to ignore that warning.

3) Assuming the `BasicBlock` you are referring to is this: https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L34, then the explainer should be able to handle it, since all of its component modules have been explicitly implemented.

**Comment by austinmw** [comment] 2019-07-17 17:10
That information helps a ton, thank you!!

(hadn't realized Flatten was part of fastai and not actually in base pytorch)

**Comment by BehnamBarabadi** [comment] 2020-12-04 02:48
> Hi Eran,
> 
> With respect to the warning, it should be fixed by this pull request: #507 . However, since a conv layer is linear, the default behaviour of the deep explainer when it doesn't recognize the module (to just take the gradient as normally calculated by pytorch) is the correct one, so the results will be correct with a conv1d layer despite the warning.
> 
> You are right; there is a bug in the max pool 1d layer; thanks for spotting it! I will look into fixing it.
> 
> You can see which modules are explicitly supported here: https://github.com/slundberg/shap/blob/master/shap/explainers/deep/deep_pytorch.py#L313
> 
> Thanks,
> 
> Gabi

Hi Gabi, 

I had a question, I'm trying to use DeepExplainer for a feedforward Linear model in PyTorch which is run on a Tabular dataset. But I couldn't find any example. Just wanted to know where can I find an example or does DeepExplainer work with Tabular data at all?
I also have a CNN model for text classification and I was curious to know if I can use DeppExplainer for that model or not??
Thank you so much in advance.

**Comment by CosmicHunter** [comment] 2020-12-30 10:48
I am using a pretrained resnet18 model in fastai for 2 class image classification. I get a similar error 
```
e = shap.DeepExplainer(learn.model, background)
```
This works fine but the below line gives error
```
shap_values = e.shap_values(test_images)
```

```
Warning: unrecognized nn.Module: Flatten
Warning: unrecognized nn.Module: AdaptiveMaxPool2d
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-63-c68d6304d8ee> in <module>()
----> 1 shap_values = e.shap_values(test_images)

7 frames
/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
    202     return Variable._execution_engine.run_backward(
    203         outputs, grad_outputs_, retain_graph, create_graph,
--> 204         inputs, allow_unused)
    205 
    206 

RuntimeError: hook 'deeplift_grad' has changed the size of value
```

The learner created in fastai is like this 
```
learn = Learner(dls, arch, loss_func=CrossEntropyLossFlat(), metrics=[accuracy, f1score],
                                opt_func=ranger,
                                 cbs=[EarlyStoppingCallback(patience = 10, monitor = 'f1_score'),
                                     SaveModelCallback(fname='cat_vs_dog_rs18',
                                                      monitor='f1_score',
                                                      reset_on_fit = False), 
                                     ReduceLROnPlateau()])
```

Could anybody suggest a fix for this?

**Comment by gabrieltseng** [comment] 2021-01-05 06:35
> Hi Gabi,
> 
> I had a question, I'm trying to use DeepExplainer for a feedforward Linear model in PyTorch which is run on a Tabular dataset. But I couldn't find any example. Just wanted to know where can I find an example or does DeepExplainer work with Tabular data at all?
> I also have a CNN model for text classification and I was curious to know if I can use DeppExplainer for that model or not??
> Thank you so much in advance.

@BehnamBarabadi the Deep Explainer should work for tabular data

**Comment by gabrieltseng** [comment] 2021-01-05 06:37
@CosmicHunter do you have a script I could use to reproduce the error? (In particular to create `dls` and `arch`).

**Comment by CosmicHunter** [comment] 2021-01-05 08:42
@gabrieltseng  This is the code for the dataloader and learner that I used.
```
tf_prob = 0.8
tf_s = 0.8


item_tfms = [Resize((376, 300), method='squish')]
batch_tfms = [Brightness(max_lighting = tf_s, p = tf_prob),
    Contrast(max_lighting = tf_s, p = tf_prob),
    Saturation(max_lighting = tf_s, p = tf_prob), Flip(tf_prob)]

db = DataBlock(blocks = (ImageBlock, CategoryBlock),
                  get_items = get_image_files,
                  splitter = GrandparentSplitter(),
                  item_tfms=item_tfms,
                  batch_tfms=batch_tfms,
                  get_y = parent_label)
```
```
dls = db.dataloaders(path, bs=32, num_worker=6)
dls.show_batch(max_n=20) 
```
Model 
```
body = create_body(resnet18, pretrained=True)
head = create_head(nf=1024, n_out=2) # head

arch = nn.Sequential(body, head)
```
```
f1score = F1Score(average = 'macro')
learn = Learner(dls, arch, loss_func=CrossEntropyLossFlat(), metrics=[accuracy, f1score],
                                opt_func=ranger,
                                 cbs=[EarlyStoppingCallback(patience = 10, monitor = 'f1_score'),
                                     SaveModelCallback(fname='cat_vs_dog_rs18',
                                                      monitor='f1_score',
                                                      reset_on_fit = False), 
                                     ReduceLROnPlateau()])
```

After this the model is trained and then SHAP is used


```
import shap
batch = next(iter(dls.train))
images, _ = batch
background = images[:20]
test_images = images[20:24]
e = shap.DeepExplainer(learn.model, background)
```
The errror comes in the below function
```
shap_values = e.shap_values(test_images)
```

**Comment by CosmicHunter** [comment] 2021-01-08 15:11
@gabrieltseng is there any fix for this?

**Comment by jaytimbadia** [comment] 2021-03-22 17:17
> Hmm... @gabrieltseng might have some ideas since he wrote the PyTorch parts.

Hi @gabrieltseng 

Wonderful work!!

This is my model

import tez
class EmotionClassifier(tez.Model):
def init(self, num_train_steps, num_classes):
super().init()
self.bert = transformers.SqueezeBertModel.from_pretrained("squeezebert/squeezebert-uncased")
self.bert_drop = nn.Dropout(0.3)
self.out = nn.Linear(768, num_classes)
self.num_train_steps = num_train_steps

def fetch_optimizer(self):
    param_optimizer = list(self.named_parameters())
    no_decay = ["bias", "LayerNorm.bias"]
    optimizer_parameters = [
        {
            "params": [
                p for n, p in param_optimizer if not any(nd in n for nd in no_decay)
            ],
            "weight_decay": 0.001,
        },
        {
            "params": [
                p for n, p in param_optimizer if any(nd in n for nd in no_decay)
            ],
            "weight_decay": 0.0,
        },
    ]
    opt = AdamW(optimizer_parameters, lr=3e-5)
    return opt



def loss(self, outputs, targets):
    if targets is None:
        return None
    return nn.BCEWithLogitsLoss()(outputs, targets.float())

def forward(self, ids, mask, targets=None):
    o_2 = self.bert(ids, attention_mask=mask)[1]
    b_o = self.bert_drop(o_2)
    output = self.out(b_o)
    loss = self.loss(output, targets)
    return output, loss
background = df2.sample(100)['comment_text'].values ## array of 100 texts
test_text = df2.sample(5)['comment_text'].values

scaffold = EmotionClassifier()
e = shap.DeepExplainer(model, background)
shap_values = e.shap_values(test_text)

Error……
c:\users\jay\py36\neo\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, *kwargs) 725 result = self._slow_forward(input, *kwargs) 726 else: --> 727 result = self.forward(input, **kwargs)
728 for hook in itertools.chain(
729 _global_forward_hooks.values(),

TypeError: forward() missing 1 required positional argument: 'mask'

Can you help me how can one use SHAP with custom pytorch model, with self.forward method returning loss as well and has two inputs?

Thanks in Advance!!
