### ISSUE TITLE
tensorflow estimator support

### ISSUE THREAD

**Issue by sathyz** [shap/shap#280] opened 2018-10-08 09:41 UTC
A request to add support for [tensorflow estimator](https://www.tensorflow.org/versions/r1.9/guide/estimators) APIs.

**Comment by slundberg** [comment] 2018-10-24 22:00
Sounds like a great idea. I don't have the bandwidth to do it right though so PRs are welcome. It might make sense to make sure whatever get implemented here is not broken by the TF 2.0 changes

**Comment by bichbich** [comment] 2019-02-07 10:37
I need it to work with shap using tf.estimator but i think it is still not supported? @slundberg

**Comment by slundberg** [comment] 2019-02-09 19:00
That's right, no one has worked on it yet that I know of.

**Comment by bichbich** [comment] 2019-02-14 16:31
@slundberg i have tried to work with tf.estimator and actually it does work BUT i don't get plots as exepected. I'm i getting it wrong or the problem is in tf.estimator itself? This is a screenshot of the results please could you help me out.
![capture](https://user-images.githubusercontent.com/25511543/52801256-c6734880-307d-11e9-83e7-fccfaf0a0cf7.PNG)

**Comment by slundberg** [comment] 2019-02-16 01:33
KernelExplainer needs to use a fair number of samples (thousands) to get a good explanation. Since you are using only 1 sample I would not expect it to return anything reasonable. Perhaps we should add a runtime warning on that...

**Comment by bichbich** [comment] 2019-02-16 17:29
Thank you @slundberg But when i changed for more than one sample i got this error ![capture1](https://user-images.githubusercontent.com/25511543/52902913-c4dd8800-3217-11e9-908b-278bb26ed75d.PNG)

**Comment by slundberg** [comment] 2019-02-16 17:48
That probably has to do with your `fct` function, it needs to accept a matrix where the rows are many samples and the columns are the features. Perhaps it is not set up to accept many rows?

**Comment by bichbich** [comment] 2019-02-16 17:56
well it does accept many rows but like you see it's transformed by tf.estimator function
input_fn_shap = tf.estimator.inputs.pandas_input_fn(
      x=train_set.drop('species', axis=1),
      y=train_set.species,
      num_epochs=1, 
      shuffle=False)

**Comment by bichbich** [comment] 2019-02-19 10:28
thank you @slundberg finally it did worked, like you did said there was an issue with my fct `def fct(d):

    train_set = pd.DataFrame(
        columns={'sepal_length','sepal_width','petal_length','petal_width','species'},
        data=d
    )
    display(train_set.head())
    x = train_set.drop('species', inplace=False, axis=1)
    y = train_set['species']  
    input_fn_shap = tf.estimator.inputs.pandas_input_fn(
      x=x,
      y=y,
      num_epochs=1, 
      shuffle=False)
    
    predictions = [p['probabilities'][0] for p in estimator.predict(input_fn=input_fn_shap)]
    return np.array(predictions)`
SHAP works perfectly with tf estimator and i have tried on many problems regression, multiclass classification.

**Comment by Dbroug01** [comment] 2019-12-16 10:45
Hi @bichbich, have you ever tried using SHAP with the DNNClassifier or DNNLinearCombinedRegressor estimators? Do you think it will work ok for those?

**Comment by bichbich** [comment] 2019-12-16 11:00
Hi @Dbroug01 yes it worked for me.

**Comment by bichbich** [comment] 2019-12-16 11:12
hi @Dbroug01 yes it works

**Comment by Dbroug01** [comment] 2019-12-16 11:43
@bichbich thanks for the quick response! Great to know.

**Comment by niloofardadras** [comment] 2020-04-22 16:51
hi,
have you by any chance tried deep explainer also?

I am trying to run tf estimator with shap.deepexplainer when i run the following:

        explainer = shap.DeepExplainer(fct(x), data=x)
        print("ohhhhyess")
        shap_values = explainer.shap_values(x_test)

my program freezes and runs forever....

also when I am running fct (without x as input)

        explainer = shap.DeepExplainer(fct , data=x)
        print("ohhhhyess")
        shap_values = explainer.shap_values(x_test)


the error message is:
AssertionError: <class 'function'> is not currently a supported model type!

also if i use

**Comment by slundberg** [comment] 2020-04-23 16:09
@niloofardadras is fct a PyTorch or TF model? DeepExplainer only supports those models, not arbitrary python fuctions.

**Comment by niloofardadras** [comment] 2020-04-23 16:22
@slundberg  thank you so much for your reply scott.
it is a tensorflow model with estimator api, I am using tensorflow 1.13. I have also tried another approach and the same issue for not getting result and loading forever is there. the issue i created yesterday is https://github.com/slundberg/shap/issues/1170.

I am in desperate need of your help. :)

**Comment by slundberg** [comment] 2020-04-23 16:49
Sorry I can't help directly debug, but if you have a very small sharable notebook example that would help get to the root of it (like a very small model on random data).

**Comment by niloofardadras** [comment] 2020-04-23 17:29
@slundberg  do you mean a model file?

**Comment by niloofardadras** [comment] 2020-04-24 15:50
@slundberg I really appreciate your help scott. I have to hopefully get this working in few days.

so here is what i did with the model files i send and now i get the explainer but there is assertion error. what i did in code is as bellow:

def convert_list(df,feature):
    '''
    :param df: Pandas dataframe
    :return: list of lists, with each categorical feature (as pd.Series) in its own list,
    and one list (of pd.DataFrame) of numeric features
    '''
    # df.apply(pd.to_numeric, errors='ignore')
    return [df[col] for col in NUMERICAl_FEATURES]+[df[col] for col in CHAR_features]


def main():
                x_train, x_test=loaddatafarme("datafile.csv")                
                sess=tf.Session()

                saver=tf.train.import_meta_graph('models/1/model.ckpt-300.meta')
                saver.restore(sess,tf.train.latest_checkpoint('model-file/'))

                graph = tf.get_default_graph()
                op=sess.graph.get_operations()
                print([m.name for m in op])

                input=graph.get_tensor_by_name('enqueue_input/Placeholder:0')
                # input = graph.get_tensor_by_name('input_layer/concat:0')

                print(input)
                print("got the input tensor")
                output=graph.get_tensor_by_name('dense/kernel/ProximalAdagrad:0')
                 explainer = shap.DeepExplainer(model=(input tensor,output 
                tensor),data=x_train_list,session=sess)
                print("explainer done")
                shap_values = explainer.shap_values(x_test_list)
                sess.close()

so now i do get the print from "explainer done" but there comes following error. 

shap_values = explainer.shap_values(x_test_list)
File "C:\Anaconda3\envs\AzureEvn\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
File "C:\Anaconda3\envs\AzureEvn\lib\site-packages\shap\explainers\deep\deep_tf.py", line 231, in shap_values
assert False, "Expected a single tensor as model input!"
AssertionError: Expected a single tensor as model input!

**Comment by niloofardadras** [comment] 2020-04-28 02:00
@slundberg hi again scot.  I also get error when I try to convert the x_test_list to np.array(x_test_list)
explainer. shap_values. 
I have dataframe with both categorical and numerical columns as my features. I am really not sure what am i doing wrong?!

error:

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Comment by niloofardadras** [comment] 2020-04-30 16:41
@slundberg  hello scott,
hope you are well these days. 
so just a quick update. I gave up on deep explainer or gradient explainer  and used the kernel explainer as used by @bichbich . It works however there is a problem. I have some categorial data that i feed to the model and it would not work at all with the categorial features as it seems to expect conversion to float. 
would you have any suggestions for making it work with the categorial columns of my data frame ?
Also is there a plan to allow estimator api models for deep explainer? 
what would be differences between the kernel explainer and deep explainer for the neural network i have. 

I use column indicators for the estimator model function. I use same tf.estimator.inputs.pandas_input_fn for converting input to tensors and i pass the input to the model to handle onehotencoding in the model.

**Comment by christabella** [comment] 2020-07-08 11:53
I think the `shap.KernelExplainer` API is incompatible with `tf.Estimator` since 
* `tf.Estimator` expects the raw inputs (e.g. "female"/"male") and handles the one-hot encoding in the model, while 
* `shap.KernelExplainer` expects the preprocessed floats (e.g. `[1, 0]`, `[0, 1]`)

For now, I will probably use the Keras library to build the model instead, following [the example KernelExplainer notebook](https://github.com/slundberg/shap/blob/master/notebooks/kernel_explainer/Census%20income%20classification%20with%20Keras.ipynb).

**Comment by NidhiSultan** [comment] 2020-08-28 11:58
> hi @Dbroug01 yes it works

@bichbich , have you tried SHAP on tf.estimator based text classification?

-->Attaching my code snippet.
-------------------------------------------
def getPrediction_lime(in_sentences):
  labels = ["Negative", "Positive"]
#   print(type(in_sentences), in_sentences)
  in_sentences=in_sentences.tolist()
  in_sentence = []
  for i in in_sentences:
        print(i[0],"jij")
        in_sentence.append(i[0])
  in_sentences = in_sentence
  print(type(in_sentences), in_sentences)
       
  input_examples = [run_classifier.InputExample(guid="", text_a = x, text_b = None, label = 0) for x in in_sentences] # here, "" is just a dummy label
  input_features = run_classifier.convert_examples_to_features(input_examples, label_list, MAX_SEQ_LENGTH, tokenizer)
  predict_input_fn = run_classifier.input_fn_builder(features=input_features, seq_length=MAX_SEQ_LENGTH, is_training=False, drop_remainder=False)
  predictions = estimator.predict(predict_input_fn)
  predict = [( prediction['probabilities'][0]) for  prediction in  predictions]#[0].tolist()
  return np.array(predict) 

import shap
# first 100 training as background
explainer = shap.KernelExplainer(getPrediction_lime, pre)
shap_values = explainer.shap_values(pred, nsamples=2)
shap.summary_plot(shap_values, pre)
---------------------------------------

shap_values = explainer.shap_values(pred, nsamples=2), this line is giving me errors like  ufunc 'isfinite' not supported for the input types, and the inputs could not be s . Can you please help me what should be the pred inside shap_values function? The label or the text?

Any help would be really appreciated. Thanks!

**Comment by niponchanda** [comment] 2021-11-27 18:31
<img width="662" alt="image" src="https://user-images.githubusercontent.com/52096113/143710637-deaae464-ac74-4f60-8b18-c22552d9c3aa.png">

I am getting the above error for the below code.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/52096113/143711981-3a13c5fd-514f-4c85-acbe-9abd68f6084d.png">

**Comment by CloseChoice** [comment] 2023-12-08 13:07
@connortann tf.Estimator is no longer actively developed, see [here](https://www.tensorflow.org/guide/estimator) so I don't see a reason to implement it in shap. I'll close this for now, feel free to reopen if needed.

**Closed as completed by CloseChoice** 2023-12-08 13:07 UTC
Labels: todo, help wanted
