### ISSUE TITLE
shap.plots.beeswarm(shap_values) -> SHAP value should be initialized

### ISSUE THREAD

**Issue by Goosang-Yu** [shap/shap#2533] opened 2022-05-03 11:53 UTC
```
explainer = shap.Explainer(my_model)
shap_values = explainer(x_test)

shap.plots.beeswarm(shap_values, max_display=21) #-> 1st run
shap.plots.beeswarm(shap_values, max_display=21) #-> 2nd run - SHAP value was changed.. 
shap.plots.beeswarm(shap_values, max_display=21) #-> 3rd run - SHAP value was changed.. 
```

when I use ploting function (beeswarm), it seems no problem at first. 
but when I run the same code at notebook right after, 
the results were changed. 

Version:
shap 0.40.0

**Comment by neiljdo** [comment] 2022-08-19 04:48
Hi @Goosang-Yu!

I think for reproducibility, you need to pass the `seed` kwarg to the `Explainer` class, like so:

```
explainer = shap.Explainer(my_model, seed=12345)
```

**Comment by thatlittleboy** [comment] 2023-07-03 01:07
Duplicate of #1970

**Closed as completed by thatlittleboy** 2023-07-03 01:07 UTC
