### ISSUE TITLE
Census Income Classification with LightGBM not reproducible - "TypeError: list indices must be integers or slices, not tuple" error

### ISSUE THREAD

**Issue by quantumds** [shap/shap#841] opened 2019-10-05 21:32 UTC
First, thanks Scott for this valuable library and your active feedback. I am trying to learn how to apply `shap` library in binary classifiers. I have tried to follow step by step the notebook that appears in the documentation [https://slundberg.github.io/shap/notebooks/Census%20income%20classification%20with%20LightGBM.html called "**_Census Income Classification with LightGBM_**" but have found an error after simply executing the jupyter notebook line-by-line

<img width="1158" alt="Error Message in Notebook" src="https://user-images.githubusercontent.com/19568551/66261070-6de8eb00-e7c7-11e9-9627-a140d7f41164.png">

. It prints: 

> **"TypeError: list indices must be integers or slices, not tuple"**.

A screenshot of my notebook and a copy of it [https://drive.google.com/file/d/1PwOts0RVjEjZfzRYIJ_HBRdrccnu6H8j/view?usp=sharing](url) is attached in this issue.

I believe this issue is related with [](https://github.com/slundberg/shap/pull/690) and the fact that before LightGBM outputted a 1D object and now it is 2D. I wonder if you guys could help me in how to modify the call to these lines in order to obtain the plots in the documentation of the library:
`explainer = shap.TreeExplainer(model)`
`shap_values = explainer.shap_values(X)`
`shap.force_plot(explainer.expected_value, shap_values[0,:], X_display.iloc[0,:])`

Or simply updating the notebook so that it could be 100% reproducible to other users of your library. Thanks in advance for all the resources. P.D. I would kindly provide a `.ipynb` fixed notebook if I knew how to obtain the mentioned outputs and am looking forward to help contributing to this tool.

**Comment by slundberg** [comment] 2019-10-09 18:33
Thanks for pointing this out! It was fixed in the ipynb version but not the HTML version. I have now updated the html version as well (which shows how it should be run with two outputs now).

**Closed as completed by slundberg** 2019-10-09 18:33 UTC

**Comment by quantumds** [comment] 2019-10-10 10:53
Hi Scott, I have just tried the link that appears in the `shap` library website with the jupyter notebook: [https://slundberg.github.io/shap/notebooks/tree_explainer/Census%20income%20classification%20with%20LightGBM.html] and it is broken. It gives the following mistake: "_**404. File not found**_".  Thanks for your answer and appreciate a lot if you can make accessible the notebook with the correct outputs! Thanks!
![LinkPage](https://user-images.githubusercontent.com/19568551/66562873-d5eb5880-eb5c-11e9-9586-5c9d3d84c1af.PNG)
![Error_Message](https://user-images.githubusercontent.com/19568551/66562878-d8e64900-eb5c-11e9-8951-f06d62edfdb5.PNG)

**Comment by quantumds** [comment] 2019-10-10 11:35
Hi Scott, one more thing. I have gone to your GitHub repo and selected the jupyter notebook that you updated. It runs perfectly well until the line of the `force_plot`: `shap.force_plot(explainer.expected_value[1], shap_values[1][0,:], X_display.iloc[0,:])`

From there it crashes in following lines. I am attaching an image of the message that I receive in the new jupyter notebook that I have downloaded from your `shap` repo.

![Error Notebook](https://user-images.githubusercontent.com/19568551/66565428-be16d300-eb62-11e9-9fa8-1d487d779966.PNG)

Thanks for all your help and support Scott.

**Comment by slundberg** [comment] 2019-10-23 03:15
Thanks! I fixed the broken link. As for the error you get though, I can't reproduce it. Do you have the most recent version of shap?

**Comment by quantumds** [comment] 2019-10-23 06:57
Epic Scott! Everything solved. Thanks a lot for your feedback and work!
