### ISSUE TITLE
SHAP for auxiliary inputs

### ISSUE THREAD

**Issue by liuhh02** [shap/shap#547] opened 2019-04-11 14:48 UTC
Hi, I am using SHAP to visualize my LSTM results. I have main and auxiliary inputs for my model - the main being the text sequence and auxiliary being quantitative features of the text. How do I use the DeepExplainer to visualize my results? I am currently typing in `shap_values = explainer.shap_values([Xtest, other_test])`, but I am getting an error 

> Traceback (most recent call last):
  File "<ipython-input-20-62fbfb1533fe>", line 1, in <module>
    shap_values = explainer.shap_values([Xtest, other_test])
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\deep_tf.py", line 257, in shap_values
    tiled_X = [np.tile(X[l][j:j+1], (bg_data[l].shape[0],) + tuple([1 for k in range(len(X[l].shape)-1)])) for l in range(len(X))]
  File "C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\deep_tf.py", line 257, in <listcomp>
    tiled_X = [np.tile(X[l][j:j+1], (bg_data[l].shape[0],) + tuple([1 for k in range(len(X[l].shape)-1)])) for l in range(len(X))]
IndexError: list index out of range

How do I resolve this problem? Thank you very much!

**Comment by thatlittleboy** [comment] 2023-06-23 13:22
Closing due to staleness and/or no example provided to reproduce, so there's no action to take here.

**Closed as not planned** 2023-06-23 13:21 UTC
